github:
  description: "Script based installer for new users trying out Apache CloudStack"
  homepage: https://get.cloudstack.cloud
  labels:
    - cloudstack
    - infrastructure
    - iaas
    - cloud
    - kvm
    - orchestration

  ghp_branch: main
  ghp_path: /

  features:
    issues: true
    discussions: true

  enabled_merge_buttons:
    merge: false
    squash: true
    rebase: false

  collaborators:
    - abh1sar
    - sudo87
    - acs-robot

  protected_branches:

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: commits@cloudstack.apache.org
  issues: commits@cloudstack.apache.org
  pullrequests: commits@cloudstack.apache.org
  discussions: users@cloudstack.apache.org
